FROM golang:1.13-alpine

WORKDIR /gateway
COPY go.mod . 
COPY go.sum .

# Get dependancies - will also be cached if we won't change mod/sum
RUN go mod download
# COPY the source code as the last step
COPY . .

CMD ["go", "run", "main.go"]
