// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthenticateRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{0}
}

func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(m, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type AuthenticateResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	IsAuthenticated      bool     `protobuf:"varint,2,opt,name=isAuthenticated,proto3" json:"isAuthenticated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateResponse) Reset()         { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()    {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{1}
}

func (m *AuthenticateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateResponse.Unmarshal(m, b)
}
func (m *AuthenticateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateResponse.Merge(m, src)
}
func (m *AuthenticateResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateResponse.Size(m)
}
func (m *AuthenticateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateResponse proto.InternalMessageInfo

func (m *AuthenticateResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *AuthenticateResponse) GetIsAuthenticated() bool {
	if m != nil {
		return m.IsAuthenticated
	}
	return false
}

type User struct {
	Auth                 *User_Auth        `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Preferences          *User_Preferences `protobuf:"bytes,2,opt,name=preferences,proto3" json:"preferences,omitempty"`
	CreatedAt            int32             `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int32             `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LoggedIn             int32             `protobuf:"varint,5,opt,name=logged_in,json=loggedIn,proto3" json:"logged_in,omitempty"`
	LoggedInIp           string            `protobuf:"bytes,6,opt,name=logged_in_ip,json=loggedInIp,proto3" json:"logged_in_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetAuth() *User_Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *User) GetPreferences() *User_Preferences {
	if m != nil {
		return m.Preferences
	}
	return nil
}

func (m *User) GetCreatedAt() int32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *User) GetUpdatedAt() int32 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *User) GetLoggedIn() int32 {
	if m != nil {
		return m.LoggedIn
	}
	return 0
}

func (m *User) GetLoggedInIp() string {
	if m != nil {
		return m.LoggedInIp
	}
	return ""
}

type User_Auth struct {
	Facebook                 *User_Auth_UserProfileFacebook `protobuf:"bytes,1,opt,name=facebook,proto3" json:"facebook,omitempty"`
	Google                   *User_Auth_UserProfileGoogle   `protobuf:"bytes,2,opt,name=google,proto3" json:"google,omitempty"`
	Email                    string                         `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Firstname                string                         `protobuf:"bytes,4,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname                 string                         `protobuf:"bytes,5,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Name                     string                         `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Picture                  string                         `protobuf:"bytes,7,opt,name=picture,proto3" json:"picture,omitempty"`
	Password                 string                         `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	PasswordHashMethod       string                         `protobuf:"bytes,9,opt,name=password_hash_method,json=passwordHashMethod,proto3" json:"password_hash_method,omitempty"`
	PasswordId               string                         `protobuf:"bytes,10,opt,name=password_id,json=passwordId,proto3" json:"password_id,omitempty"`
	PasswordResetToken       string                         `protobuf:"bytes,11,opt,name=password_reset_token,json=passwordResetToken,proto3" json:"password_reset_token,omitempty"`
	PasswordResetExpires     int32                          `protobuf:"varint,12,opt,name=password_reset_expires,json=passwordResetExpires,proto3" json:"password_reset_expires,omitempty"`
	PasswordModified         int32                          `protobuf:"varint,13,opt,name=password_modified,json=passwordModified,proto3" json:"password_modified,omitempty"`
	Verified                 bool                           `protobuf:"varint,14,opt,name=verified,proto3" json:"verified,omitempty"`
	VerifiedDate             int32                          `protobuf:"varint,15,opt,name=verified_date,json=verifiedDate,proto3" json:"verified_date,omitempty"`
	VerificationToken        string                         `protobuf:"bytes,16,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"`
	VerificationTokenExpires int32                          `protobuf:"varint,17,opt,name=verification_token_expires,json=verificationTokenExpires,proto3" json:"verification_token_expires,omitempty"`
	CaptchaChallengeTs       int32                          `protobuf:"varint,18,opt,name=captcha_challenge_ts,json=captchaChallengeTs,proto3" json:"captcha_challenge_ts,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                       `json:"-"`
	XXX_unrecognized         []byte                         `json:"-"`
	XXX_sizecache            int32                          `json:"-"`
}

func (m *User_Auth) Reset()         { *m = User_Auth{} }
func (m *User_Auth) String() string { return proto.CompactTextString(m) }
func (*User_Auth) ProtoMessage()    {}
func (*User_Auth) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{2, 0}
}

func (m *User_Auth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_Auth.Unmarshal(m, b)
}
func (m *User_Auth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_Auth.Marshal(b, m, deterministic)
}
func (m *User_Auth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_Auth.Merge(m, src)
}
func (m *User_Auth) XXX_Size() int {
	return xxx_messageInfo_User_Auth.Size(m)
}
func (m *User_Auth) XXX_DiscardUnknown() {
	xxx_messageInfo_User_Auth.DiscardUnknown(m)
}

var xxx_messageInfo_User_Auth proto.InternalMessageInfo

func (m *User_Auth) GetFacebook() *User_Auth_UserProfileFacebook {
	if m != nil {
		return m.Facebook
	}
	return nil
}

func (m *User_Auth) GetGoogle() *User_Auth_UserProfileGoogle {
	if m != nil {
		return m.Google
	}
	return nil
}

func (m *User_Auth) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User_Auth) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *User_Auth) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *User_Auth) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User_Auth) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *User_Auth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User_Auth) GetPasswordHashMethod() string {
	if m != nil {
		return m.PasswordHashMethod
	}
	return ""
}

func (m *User_Auth) GetPasswordId() string {
	if m != nil {
		return m.PasswordId
	}
	return ""
}

func (m *User_Auth) GetPasswordResetToken() string {
	if m != nil {
		return m.PasswordResetToken
	}
	return ""
}

func (m *User_Auth) GetPasswordResetExpires() int32 {
	if m != nil {
		return m.PasswordResetExpires
	}
	return 0
}

func (m *User_Auth) GetPasswordModified() int32 {
	if m != nil {
		return m.PasswordModified
	}
	return 0
}

func (m *User_Auth) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *User_Auth) GetVerifiedDate() int32 {
	if m != nil {
		return m.VerifiedDate
	}
	return 0
}

func (m *User_Auth) GetVerificationToken() string {
	if m != nil {
		return m.VerificationToken
	}
	return ""
}

func (m *User_Auth) GetVerificationTokenExpires() int32 {
	if m != nil {
		return m.VerificationTokenExpires
	}
	return 0
}

func (m *User_Auth) GetCaptchaChallengeTs() int32 {
	if m != nil {
		return m.CaptchaChallengeTs
	}
	return 0
}

type User_Auth_ProfileName struct {
	FamilyName           string   `protobuf:"bytes,1,opt,name=familyName,proto3" json:"familyName,omitempty"`
	GivenName            string   `protobuf:"bytes,2,opt,name=givenName,proto3" json:"givenName,omitempty"`
	MiddleName           string   `protobuf:"bytes,3,opt,name=middleName,proto3" json:"middleName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_Auth_ProfileName) Reset()         { *m = User_Auth_ProfileName{} }
func (m *User_Auth_ProfileName) String() string { return proto.CompactTextString(m) }
func (*User_Auth_ProfileName) ProtoMessage()    {}
func (*User_Auth_ProfileName) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{2, 0, 0}
}

func (m *User_Auth_ProfileName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_Auth_ProfileName.Unmarshal(m, b)
}
func (m *User_Auth_ProfileName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_Auth_ProfileName.Marshal(b, m, deterministic)
}
func (m *User_Auth_ProfileName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_Auth_ProfileName.Merge(m, src)
}
func (m *User_Auth_ProfileName) XXX_Size() int {
	return xxx_messageInfo_User_Auth_ProfileName.Size(m)
}
func (m *User_Auth_ProfileName) XXX_DiscardUnknown() {
	xxx_messageInfo_User_Auth_ProfileName.DiscardUnknown(m)
}

var xxx_messageInfo_User_Auth_ProfileName proto.InternalMessageInfo

func (m *User_Auth_ProfileName) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *User_Auth_ProfileName) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *User_Auth_ProfileName) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

type User_Auth_ProfileEmails struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_Auth_ProfileEmails) Reset()         { *m = User_Auth_ProfileEmails{} }
func (m *User_Auth_ProfileEmails) String() string { return proto.CompactTextString(m) }
func (*User_Auth_ProfileEmails) ProtoMessage()    {}
func (*User_Auth_ProfileEmails) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{2, 0, 1}
}

func (m *User_Auth_ProfileEmails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_Auth_ProfileEmails.Unmarshal(m, b)
}
func (m *User_Auth_ProfileEmails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_Auth_ProfileEmails.Marshal(b, m, deterministic)
}
func (m *User_Auth_ProfileEmails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_Auth_ProfileEmails.Merge(m, src)
}
func (m *User_Auth_ProfileEmails) XXX_Size() int {
	return xxx_messageInfo_User_Auth_ProfileEmails.Size(m)
}
func (m *User_Auth_ProfileEmails) XXX_DiscardUnknown() {
	xxx_messageInfo_User_Auth_ProfileEmails.DiscardUnknown(m)
}

var xxx_messageInfo_User_Auth_ProfileEmails proto.InternalMessageInfo

func (m *User_Auth_ProfileEmails) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *User_Auth_ProfileEmails) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type User_Auth_ProfilePhotos struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_Auth_ProfilePhotos) Reset()         { *m = User_Auth_ProfilePhotos{} }
func (m *User_Auth_ProfilePhotos) String() string { return proto.CompactTextString(m) }
func (*User_Auth_ProfilePhotos) ProtoMessage()    {}
func (*User_Auth_ProfilePhotos) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{2, 0, 2}
}

func (m *User_Auth_ProfilePhotos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_Auth_ProfilePhotos.Unmarshal(m, b)
}
func (m *User_Auth_ProfilePhotos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_Auth_ProfilePhotos.Marshal(b, m, deterministic)
}
func (m *User_Auth_ProfilePhotos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_Auth_ProfilePhotos.Merge(m, src)
}
func (m *User_Auth_ProfilePhotos) XXX_Size() int {
	return xxx_messageInfo_User_Auth_ProfilePhotos.Size(m)
}
func (m *User_Auth_ProfilePhotos) XXX_DiscardUnknown() {
	xxx_messageInfo_User_Auth_ProfilePhotos.DiscardUnknown(m)
}

var xxx_messageInfo_User_Auth_ProfilePhotos proto.InternalMessageInfo

func (m *User_Auth_ProfilePhotos) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type User_Auth_UserProfileFacebook struct {
	Provider             string                     `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Id                   string                     `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName          string                     `protobuf:"bytes,3,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Name                 *User_Auth_ProfileName     `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Emails               []*User_Auth_ProfileEmails `protobuf:"bytes,5,rep,name=emails,proto3" json:"emails,omitempty"`
	Photos               []*User_Auth_ProfilePhotos `protobuf:"bytes,6,rep,name=photos,proto3" json:"photos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *User_Auth_UserProfileFacebook) Reset()         { *m = User_Auth_UserProfileFacebook{} }
func (m *User_Auth_UserProfileFacebook) String() string { return proto.CompactTextString(m) }
func (*User_Auth_UserProfileFacebook) ProtoMessage()    {}
func (*User_Auth_UserProfileFacebook) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{2, 0, 3}
}

func (m *User_Auth_UserProfileFacebook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_Auth_UserProfileFacebook.Unmarshal(m, b)
}
func (m *User_Auth_UserProfileFacebook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_Auth_UserProfileFacebook.Marshal(b, m, deterministic)
}
func (m *User_Auth_UserProfileFacebook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_Auth_UserProfileFacebook.Merge(m, src)
}
func (m *User_Auth_UserProfileFacebook) XXX_Size() int {
	return xxx_messageInfo_User_Auth_UserProfileFacebook.Size(m)
}
func (m *User_Auth_UserProfileFacebook) XXX_DiscardUnknown() {
	xxx_messageInfo_User_Auth_UserProfileFacebook.DiscardUnknown(m)
}

var xxx_messageInfo_User_Auth_UserProfileFacebook proto.InternalMessageInfo

func (m *User_Auth_UserProfileFacebook) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *User_Auth_UserProfileFacebook) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User_Auth_UserProfileFacebook) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *User_Auth_UserProfileFacebook) GetName() *User_Auth_ProfileName {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *User_Auth_UserProfileFacebook) GetEmails() []*User_Auth_ProfileEmails {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *User_Auth_UserProfileFacebook) GetPhotos() []*User_Auth_ProfilePhotos {
	if m != nil {
		return m.Photos
	}
	return nil
}

type User_Auth_UserProfileGoogle struct {
	Provider             string                     `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Id                   string                     `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName          string                     `protobuf:"bytes,3,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Name                 *User_Auth_ProfileName     `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Emails               []*User_Auth_ProfileEmails `protobuf:"bytes,5,rep,name=emails,proto3" json:"emails,omitempty"`
	Photos               []*User_Auth_ProfilePhotos `protobuf:"bytes,6,rep,name=photos,proto3" json:"photos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *User_Auth_UserProfileGoogle) Reset()         { *m = User_Auth_UserProfileGoogle{} }
func (m *User_Auth_UserProfileGoogle) String() string { return proto.CompactTextString(m) }
func (*User_Auth_UserProfileGoogle) ProtoMessage()    {}
func (*User_Auth_UserProfileGoogle) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{2, 0, 4}
}

func (m *User_Auth_UserProfileGoogle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_Auth_UserProfileGoogle.Unmarshal(m, b)
}
func (m *User_Auth_UserProfileGoogle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_Auth_UserProfileGoogle.Marshal(b, m, deterministic)
}
func (m *User_Auth_UserProfileGoogle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_Auth_UserProfileGoogle.Merge(m, src)
}
func (m *User_Auth_UserProfileGoogle) XXX_Size() int {
	return xxx_messageInfo_User_Auth_UserProfileGoogle.Size(m)
}
func (m *User_Auth_UserProfileGoogle) XXX_DiscardUnknown() {
	xxx_messageInfo_User_Auth_UserProfileGoogle.DiscardUnknown(m)
}

var xxx_messageInfo_User_Auth_UserProfileGoogle proto.InternalMessageInfo

func (m *User_Auth_UserProfileGoogle) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *User_Auth_UserProfileGoogle) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User_Auth_UserProfileGoogle) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *User_Auth_UserProfileGoogle) GetName() *User_Auth_ProfileName {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *User_Auth_UserProfileGoogle) GetEmails() []*User_Auth_ProfileEmails {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *User_Auth_UserProfileGoogle) GetPhotos() []*User_Auth_ProfilePhotos {
	if m != nil {
		return m.Photos
	}
	return nil
}

// Preferences
type User_Preferences struct {
	Language             string                               `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	EmailNotifications   *User_Preferences_EmailNotifications `protobuf:"bytes,2,opt,name=email_notifications,json=emailNotifications,proto3" json:"email_notifications,omitempty"`
	PushNotifications    *User_Preferences_PushNotifications  `protobuf:"bytes,3,opt,name=push_notifications,json=pushNotifications,proto3" json:"push_notifications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *User_Preferences) Reset()         { *m = User_Preferences{} }
func (m *User_Preferences) String() string { return proto.CompactTextString(m) }
func (*User_Preferences) ProtoMessage()    {}
func (*User_Preferences) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{2, 1}
}

func (m *User_Preferences) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_Preferences.Unmarshal(m, b)
}
func (m *User_Preferences) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_Preferences.Marshal(b, m, deterministic)
}
func (m *User_Preferences) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_Preferences.Merge(m, src)
}
func (m *User_Preferences) XXX_Size() int {
	return xxx_messageInfo_User_Preferences.Size(m)
}
func (m *User_Preferences) XXX_DiscardUnknown() {
	xxx_messageInfo_User_Preferences.DiscardUnknown(m)
}

var xxx_messageInfo_User_Preferences proto.InternalMessageInfo

func (m *User_Preferences) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *User_Preferences) GetEmailNotifications() *User_Preferences_EmailNotifications {
	if m != nil {
		return m.EmailNotifications
	}
	return nil
}

func (m *User_Preferences) GetPushNotifications() *User_Preferences_PushNotifications {
	if m != nil {
		return m.PushNotifications
	}
	return nil
}

type User_Preferences_EmailNotifications struct {
	UnsubscribeFromAll   bool     `protobuf:"varint,1,opt,name=unsubscribe_from_all,json=unsubscribeFromAll,proto3" json:"unsubscribe_from_all,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_Preferences_EmailNotifications) Reset()         { *m = User_Preferences_EmailNotifications{} }
func (m *User_Preferences_EmailNotifications) String() string { return proto.CompactTextString(m) }
func (*User_Preferences_EmailNotifications) ProtoMessage()    {}
func (*User_Preferences_EmailNotifications) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{2, 1, 0}
}

func (m *User_Preferences_EmailNotifications) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_Preferences_EmailNotifications.Unmarshal(m, b)
}
func (m *User_Preferences_EmailNotifications) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_Preferences_EmailNotifications.Marshal(b, m, deterministic)
}
func (m *User_Preferences_EmailNotifications) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_Preferences_EmailNotifications.Merge(m, src)
}
func (m *User_Preferences_EmailNotifications) XXX_Size() int {
	return xxx_messageInfo_User_Preferences_EmailNotifications.Size(m)
}
func (m *User_Preferences_EmailNotifications) XXX_DiscardUnknown() {
	xxx_messageInfo_User_Preferences_EmailNotifications.DiscardUnknown(m)
}

var xxx_messageInfo_User_Preferences_EmailNotifications proto.InternalMessageInfo

func (m *User_Preferences_EmailNotifications) GetUnsubscribeFromAll() bool {
	if m != nil {
		return m.UnsubscribeFromAll
	}
	return false
}

type User_Preferences_PushNotifications struct {
	UnsubscribeFromAll   bool     `protobuf:"varint,1,opt,name=unsubscribe_from_all,json=unsubscribeFromAll,proto3" json:"unsubscribe_from_all,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_Preferences_PushNotifications) Reset()         { *m = User_Preferences_PushNotifications{} }
func (m *User_Preferences_PushNotifications) String() string { return proto.CompactTextString(m) }
func (*User_Preferences_PushNotifications) ProtoMessage()    {}
func (*User_Preferences_PushNotifications) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{2, 1, 1}
}

func (m *User_Preferences_PushNotifications) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_Preferences_PushNotifications.Unmarshal(m, b)
}
func (m *User_Preferences_PushNotifications) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_Preferences_PushNotifications.Marshal(b, m, deterministic)
}
func (m *User_Preferences_PushNotifications) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_Preferences_PushNotifications.Merge(m, src)
}
func (m *User_Preferences_PushNotifications) XXX_Size() int {
	return xxx_messageInfo_User_Preferences_PushNotifications.Size(m)
}
func (m *User_Preferences_PushNotifications) XXX_DiscardUnknown() {
	xxx_messageInfo_User_Preferences_PushNotifications.DiscardUnknown(m)
}

var xxx_messageInfo_User_Preferences_PushNotifications proto.InternalMessageInfo

func (m *User_Preferences_PushNotifications) GetUnsubscribeFromAll() bool {
	if m != nil {
		return m.UnsubscribeFromAll
	}
	return false
}

func init() {
	proto.RegisterType((*AuthenticateRequest)(nil), "auth.AuthenticateRequest")
	proto.RegisterType((*AuthenticateResponse)(nil), "auth.AuthenticateResponse")
	proto.RegisterType((*User)(nil), "auth.User")
	proto.RegisterType((*User_Auth)(nil), "auth.User.Auth")
	proto.RegisterType((*User_Auth_ProfileName)(nil), "auth.User.Auth.ProfileName")
	proto.RegisterType((*User_Auth_ProfileEmails)(nil), "auth.User.Auth.ProfileEmails")
	proto.RegisterType((*User_Auth_ProfilePhotos)(nil), "auth.User.Auth.ProfilePhotos")
	proto.RegisterType((*User_Auth_UserProfileFacebook)(nil), "auth.User.Auth.UserProfileFacebook")
	proto.RegisterType((*User_Auth_UserProfileGoogle)(nil), "auth.User.Auth.UserProfileGoogle")
	proto.RegisterType((*User_Preferences)(nil), "auth.User.Preferences")
	proto.RegisterType((*User_Preferences_EmailNotifications)(nil), "auth.User.Preferences.EmailNotifications")
	proto.RegisterType((*User_Preferences_PushNotifications)(nil), "auth.User.Preferences.PushNotifications")
}

func init() { proto.RegisterFile("auth/auth.proto", fileDescriptor_712ec48c1eaf43a2) }

var fileDescriptor_712ec48c1eaf43a2 = []byte{
	// 904 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x56, 0x6d, 0x6f, 0xe3, 0x44,
	0x10, 0xa6, 0x69, 0x92, 0x4b, 0xc6, 0xed, 0xa5, 0x99, 0x46, 0x27, 0xe3, 0xe3, 0x8e, 0xd0, 0x0a,
	0x29, 0x08, 0xd1, 0x3b, 0xf5, 0x40, 0xe2, 0x24, 0x24, 0x54, 0x41, 0x0b, 0x41, 0xba, 0x53, 0x65,
	0x0e, 0x21, 0xf8, 0x62, 0xb6, 0xf6, 0x26, 0x5e, 0xd5, 0xf1, 0x1a, 0xef, 0x3a, 0xd0, 0x6f, 0x88,
	0x5f, 0xc0, 0xff, 0xe1, 0x37, 0xf1, 0x1f, 0xd0, 0x8e, 0xd7, 0x8e, 0xf3, 0xd2, 0x93, 0xf8, 0xcc,
	0x97, 0x68, 0xe7, 0x79, 0xe6, 0x99, 0xcd, 0xb3, 0x9e, 0xb1, 0x17, 0x06, 0xac, 0xd0, 0xf1, 0x33,
	0xf3, 0x73, 0x96, 0xe5, 0x52, 0x4b, 0x6c, 0x9b, 0xf5, 0xc9, 0x0b, 0x38, 0xbe, 0x28, 0x74, 0xcc,
	0x53, 0x2d, 0x42, 0xa6, 0xb9, 0xcf, 0x7f, 0x2d, 0xb8, 0xd2, 0xf8, 0x1e, 0xf4, 0x15, 0x57, 0x4a,
	0xc8, 0x74, 0x1a, 0xb9, 0x7b, 0xe3, 0xbd, 0x49, 0xdf, 0x5f, 0x01, 0x27, 0xbf, 0xc0, 0x68, 0x5d,
	0xa4, 0x32, 0x99, 0x2a, 0x8e, 0x4f, 0xa1, 0x5d, 0x28, 0x9e, 0x93, 0xc0, 0x39, 0x87, 0x33, 0xda,
	0xed, 0x07, 0xc5, 0x73, 0x9f, 0x70, 0x9c, 0xc0, 0x40, 0xa8, 0xa6, 0x32, 0x72, 0x5b, 0xe3, 0xbd,
	0x49, 0xcf, 0xdf, 0x84, 0x4f, 0xfe, 0x3a, 0x82, 0xb6, 0x11, 0xe2, 0x29, 0xd0, 0xff, 0xb4, 0x25,
	0x07, 0xab, 0x92, 0x67, 0x46, 0xe0, 0x13, 0x89, 0x9f, 0x83, 0x93, 0xe5, 0x7c, 0xc6, 0x73, 0x9e,
	0x86, 0x5c, 0x51, 0x4d, 0xe7, 0xfc, 0x51, 0x23, 0xf7, 0x7a, 0xc5, 0xfa, 0xcd, 0x54, 0x7c, 0x02,
	0x10, 0xe6, 0xdc, 0x6c, 0x19, 0x30, 0xed, 0xee, 0x8f, 0xf7, 0x26, 0x1d, 0xbf, 0x6f, 0x91, 0x0b,
	0x6d, 0xe8, 0x22, 0x8b, 0x2a, 0xba, 0x5d, 0xd2, 0x16, 0xb9, 0xd0, 0xf8, 0x18, 0xfa, 0x89, 0x9c,
	0xcf, 0x79, 0x14, 0x88, 0xd4, 0xed, 0x10, 0xdb, 0x2b, 0x81, 0x69, 0x8a, 0x63, 0x38, 0xa8, 0xc9,
	0x40, 0x64, 0x6e, 0x97, 0x4e, 0x11, 0x2a, 0x7e, 0x9a, 0x79, 0x7f, 0x3b, 0xd0, 0x36, 0x2e, 0xf0,
	0x4b, 0xe8, 0xcd, 0x58, 0xc8, 0x6f, 0xa4, 0xbc, 0xb5, 0x46, 0x4f, 0x37, 0x8c, 0xd2, 0xea, 0x3a,
	0x97, 0x33, 0x91, 0xf0, 0x2b, 0x9b, 0xea, 0xd7, 0x22, 0x7c, 0x09, 0xdd, 0xb9, 0x94, 0xf3, 0x84,
	0x5b, 0xef, 0x1f, 0xbc, 0x45, 0xfe, 0x0d, 0x25, 0xfa, 0x56, 0x80, 0x23, 0xe8, 0xf0, 0x05, 0x13,
	0x09, 0x99, 0xef, 0xfb, 0x65, 0x60, 0x9e, 0xff, 0x4c, 0xe4, 0x4a, 0xa7, 0x6c, 0xc1, 0xc9, 0x77,
	0xdf, 0x5f, 0x01, 0xe8, 0x41, 0x2f, 0x61, 0x96, 0xec, 0x10, 0x59, 0xc7, 0x88, 0xd0, 0x26, 0xbc,
	0xb4, 0x4b, 0x6b, 0x74, 0xe1, 0x41, 0x26, 0x42, 0x5d, 0xe4, 0xdc, 0x7d, 0x40, 0x70, 0x15, 0x9a,
	0x4a, 0x19, 0x53, 0xea, 0x37, 0x99, 0x47, 0x6e, 0xaf, 0xac, 0x54, 0xc5, 0xf8, 0x1c, 0x46, 0xd5,
	0x3a, 0x88, 0x99, 0x8a, 0x83, 0x05, 0xd7, 0xb1, 0x8c, 0xdc, 0x3e, 0xe5, 0x61, 0xc5, 0x7d, 0xcb,
	0x54, 0xfc, 0x8a, 0x18, 0x7c, 0x1f, 0x9c, 0x5a, 0x21, 0x22, 0x17, 0xca, 0x13, 0xaf, 0xa0, 0xe9,
	0x7a, 0xc9, 0x9c, 0x2b, 0xae, 0x03, 0x2d, 0x6f, 0x79, 0xea, 0x3a, 0xeb, 0x25, 0x7d, 0x43, 0xbd,
	0x31, 0x0c, 0x7e, 0x0a, 0x8f, 0x36, 0x14, 0xfc, 0xf7, 0x4c, 0xe4, 0x5c, 0xb9, 0x07, 0xf4, 0xbc,
	0x47, 0x6b, 0x9a, 0xcb, 0x92, 0xc3, 0x8f, 0x61, 0x58, 0xab, 0x16, 0x32, 0x12, 0x33, 0xc1, 0x23,
	0xf7, 0x90, 0x04, 0x47, 0x15, 0xf1, 0xca, 0xe2, 0xe6, 0x0c, 0x96, 0x3c, 0x2f, 0x73, 0x1e, 0xd2,
	0x38, 0xd4, 0x31, 0x9e, 0xc2, 0x61, 0xb5, 0x0e, 0x4c, 0xd7, 0xb9, 0x03, 0x2a, 0x72, 0x50, 0x81,
	0x5f, 0x33, 0xcd, 0xf1, 0x13, 0xc0, 0x32, 0x0e, 0x99, 0x16, 0x32, 0xb5, 0x9e, 0x8e, 0xc8, 0xd3,
	0xb0, 0xc9, 0x94, 0x96, 0xbe, 0x00, 0x6f, 0x3b, 0xbd, 0xb6, 0x35, 0xa4, 0x0d, 0xdc, 0x2d, 0x59,
	0x65, 0xed, 0x39, 0x8c, 0x42, 0x96, 0xe9, 0x30, 0x66, 0x41, 0x18, 0xb3, 0x24, 0xe1, 0xe9, 0x9c,
	0x07, 0x5a, 0xb9, 0x48, 0x3a, 0xb4, 0xdc, 0x57, 0x15, 0xf5, 0x46, 0x79, 0xb7, 0xe0, 0xd8, 0xd6,
	0x7b, 0x6d, 0x9a, 0xe1, 0x29, 0xc0, 0x8c, 0x2d, 0x44, 0x72, 0x67, 0x22, 0xfb, 0x6e, 0x69, 0x20,
	0xa6, 0xf5, 0xe6, 0x62, 0xc9, 0x53, 0xa2, 0x5b, 0x65, 0xeb, 0xd5, 0x80, 0x51, 0x2f, 0x44, 0x14,
	0x95, 0xb5, 0x6c, 0xcf, 0x36, 0x10, 0xef, 0x25, 0x1c, 0xda, 0xcd, 0x2e, 0x4d, 0x23, 0x2b, 0xd3,
	0xdf, 0x4b, 0x96, 0x14, 0xd5, 0x4e, 0x65, 0x60, 0xba, 0x54, 0xdf, 0x65, 0x55, 0x7d, 0x5a, 0x7b,
	0x1f, 0xd6, 0xd2, 0xeb, 0x58, 0x6a, 0x79, 0x8f, 0xd4, 0xfb, 0xb3, 0x05, 0xc7, 0x3b, 0xa6, 0x91,
	0x5a, 0x39, 0x97, 0x4b, 0x11, 0xd9, 0x17, 0xa0, 0x69, 0x65, 0x1b, 0xe3, 0x43, 0x68, 0x89, 0xc8,
	0x6e, 0xd6, 0x12, 0x11, 0x8e, 0xc1, 0x89, 0x84, 0xca, 0x12, 0x76, 0xd7, 0xb0, 0xd1, 0x84, 0xf0,
	0x99, 0x1d, 0xa3, 0x36, 0xcd, 0xf3, 0xe3, 0xcd, 0x79, 0x6e, 0x1c, 0xa8, 0x9d, 0xb1, 0xcf, 0xa0,
	0x4b, 0xa3, 0xab, 0xdc, 0xce, 0x78, 0x7f, 0xe2, 0x9c, 0x3f, 0xb9, 0x47, 0x52, 0x1e, 0x8b, 0x6f,
	0x93, 0x8d, 0x2c, 0x23, 0xb7, 0x6e, 0xf7, 0xad, 0xb2, 0xf2, 0x48, 0x7c, 0x9b, 0xec, 0xfd, 0xd1,
	0x82, 0xe1, 0xd6, 0x3b, 0xe5, 0xff, 0x75, 0x04, 0xff, 0xb4, 0x4c, 0x5f, 0xaf, 0x3e, 0x25, 0xf4,
	0x52, 0x4c, 0xe7, 0x05, 0x9b, 0x57, 0x0d, 0x53, 0xc7, 0xf8, 0x33, 0x1c, 0xd3, 0x66, 0x41, 0x2a,
	0x75, 0x3d, 0x56, 0xd5, 0x87, 0xea, 0xa3, 0xdd, 0x1f, 0xaa, 0x33, 0xfa, 0x9b, 0xaf, 0x9b, 0x02,
	0x1f, 0xf9, 0x16, 0x86, 0x3f, 0x02, 0x66, 0x85, 0x8a, 0x37, 0x4a, 0xef, 0x53, 0xe9, 0xc9, 0x3d,
	0xa5, 0xaf, 0x0b, 0x15, 0xaf, 0x57, 0x1e, 0x66, 0x9b, 0x90, 0x77, 0x05, 0xb8, 0xfd, 0x17, 0xcc,
	0xfc, 0x17, 0xa9, 0x2a, 0x6e, 0x54, 0x98, 0x8b, 0x1b, 0x1e, 0xcc, 0x72, 0xb9, 0x08, 0x58, 0x92,
	0x90, 0xe5, 0x9e, 0x8f, 0x0d, 0xee, 0x2a, 0x97, 0x8b, 0x8b, 0x24, 0xf1, 0x2e, 0x61, 0xb8, 0xb5,
	0xdf, 0x7f, 0x2f, 0x73, 0xfe, 0x13, 0x38, 0xe6, 0x69, 0x7c, 0xcf, 0xf3, 0xa5, 0x08, 0x39, 0x7e,
	0x07, 0x83, 0xe9, 0xfa, 0xa5, 0x01, 0xdf, 0x2d, 0xdd, 0xee, 0xb8, 0xcf, 0x78, 0xde, 0x2e, 0xaa,
	0xbc, 0xb5, 0x9c, 0xbc, 0x73, 0xd3, 0xa5, 0x1b, 0xd1, 0x8b, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x7c, 0x4b, 0xe9, 0x00, 0x24, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	IsAuthenticated(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) IsAuthenticated(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/IsAuthenticated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	IsAuthenticated(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) IsAuthenticated(ctx context.Context, req *AuthenticateRequest) (*AuthenticateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAuthenticated not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_IsAuthenticated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).IsAuthenticated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/IsAuthenticated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).IsAuthenticated(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsAuthenticated",
			Handler:    _AuthService_IsAuthenticated_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/auth.proto",
}
