// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment/payment.proto

package payment

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreatePaymentRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePaymentRequest) Reset()         { *m = CreatePaymentRequest{} }
func (m *CreatePaymentRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePaymentRequest) ProtoMessage()    {}
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a39aceed8019db, []int{0}
}

func (m *CreatePaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePaymentRequest.Unmarshal(m, b)
}
func (m *CreatePaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePaymentRequest.Marshal(b, m, deterministic)
}
func (m *CreatePaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePaymentRequest.Merge(m, src)
}
func (m *CreatePaymentRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePaymentRequest.Size(m)
}
func (m *CreatePaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePaymentRequest proto.InternalMessageInfo

func (m *CreatePaymentRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *CreatePaymentRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreatePaymentResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Payment              *Payment `protobuf:"bytes,2,opt,name=payment,proto3" json:"payment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePaymentResponse) Reset()         { *m = CreatePaymentResponse{} }
func (m *CreatePaymentResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePaymentResponse) ProtoMessage()    {}
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a39aceed8019db, []int{1}
}

func (m *CreatePaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePaymentResponse.Unmarshal(m, b)
}
func (m *CreatePaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePaymentResponse.Marshal(b, m, deterministic)
}
func (m *CreatePaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePaymentResponse.Merge(m, src)
}
func (m *CreatePaymentResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePaymentResponse.Size(m)
}
func (m *CreatePaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePaymentResponse proto.InternalMessageInfo

func (m *CreatePaymentResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreatePaymentResponse) GetPayment() *Payment {
	if m != nil {
		return m.Payment
	}
	return nil
}

type RetrievePaymentRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrievePaymentRequest) Reset()         { *m = RetrievePaymentRequest{} }
func (m *RetrievePaymentRequest) String() string { return proto.CompactTextString(m) }
func (*RetrievePaymentRequest) ProtoMessage()    {}
func (*RetrievePaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a39aceed8019db, []int{2}
}

func (m *RetrievePaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrievePaymentRequest.Unmarshal(m, b)
}
func (m *RetrievePaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrievePaymentRequest.Marshal(b, m, deterministic)
}
func (m *RetrievePaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrievePaymentRequest.Merge(m, src)
}
func (m *RetrievePaymentRequest) XXX_Size() int {
	return xxx_messageInfo_RetrievePaymentRequest.Size(m)
}
func (m *RetrievePaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrievePaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrievePaymentRequest proto.InternalMessageInfo

func (m *RetrievePaymentRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type RetrievePaymentResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Payment              *Payment `protobuf:"bytes,2,opt,name=payment,proto3" json:"payment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrievePaymentResponse) Reset()         { *m = RetrievePaymentResponse{} }
func (m *RetrievePaymentResponse) String() string { return proto.CompactTextString(m) }
func (*RetrievePaymentResponse) ProtoMessage()    {}
func (*RetrievePaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a39aceed8019db, []int{3}
}

func (m *RetrievePaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrievePaymentResponse.Unmarshal(m, b)
}
func (m *RetrievePaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrievePaymentResponse.Marshal(b, m, deterministic)
}
func (m *RetrievePaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrievePaymentResponse.Merge(m, src)
}
func (m *RetrievePaymentResponse) XXX_Size() int {
	return xxx_messageInfo_RetrievePaymentResponse.Size(m)
}
func (m *RetrievePaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrievePaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetrievePaymentResponse proto.InternalMessageInfo

func (m *RetrievePaymentResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RetrievePaymentResponse) GetPayment() *Payment {
	if m != nil {
		return m.Payment
	}
	return nil
}

type RefundRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Transaction          string   `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefundRequest) Reset()         { *m = RefundRequest{} }
func (m *RefundRequest) String() string { return proto.CompactTextString(m) }
func (*RefundRequest) ProtoMessage()    {}
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a39aceed8019db, []int{4}
}

func (m *RefundRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefundRequest.Unmarshal(m, b)
}
func (m *RefundRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefundRequest.Marshal(b, m, deterministic)
}
func (m *RefundRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefundRequest.Merge(m, src)
}
func (m *RefundRequest) XXX_Size() int {
	return xxx_messageInfo_RefundRequest.Size(m)
}
func (m *RefundRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefundRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefundRequest proto.InternalMessageInfo

func (m *RefundRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *RefundRequest) GetTransaction() string {
	if m != nil {
		return m.Transaction
	}
	return ""
}

type RefundResponse struct {
	Success              bool         `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Refund               *Refund      `protobuf:"bytes,2,opt,name=refund,proto3" json:"refund,omitempty"`
	Transaction          *Transaction `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RefundResponse) Reset()         { *m = RefundResponse{} }
func (m *RefundResponse) String() string { return proto.CompactTextString(m) }
func (*RefundResponse) ProtoMessage()    {}
func (*RefundResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a39aceed8019db, []int{5}
}

func (m *RefundResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefundResponse.Unmarshal(m, b)
}
func (m *RefundResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefundResponse.Marshal(b, m, deterministic)
}
func (m *RefundResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefundResponse.Merge(m, src)
}
func (m *RefundResponse) XXX_Size() int {
	return xxx_messageInfo_RefundResponse.Size(m)
}
func (m *RefundResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefundResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefundResponse proto.InternalMessageInfo

func (m *RefundResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RefundResponse) GetRefund() *Refund {
	if m != nil {
		return m.Refund
	}
	return nil
}

func (m *RefundResponse) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type AddCardRequest struct {
	PaymentMethod        string   `protobuf:"bytes,1,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCardRequest) Reset()         { *m = AddCardRequest{} }
func (m *AddCardRequest) String() string { return proto.CompactTextString(m) }
func (*AddCardRequest) ProtoMessage()    {}
func (*AddCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a39aceed8019db, []int{6}
}

func (m *AddCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCardRequest.Unmarshal(m, b)
}
func (m *AddCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCardRequest.Marshal(b, m, deterministic)
}
func (m *AddCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCardRequest.Merge(m, src)
}
func (m *AddCardRequest) XXX_Size() int {
	return xxx_messageInfo_AddCardRequest.Size(m)
}
func (m *AddCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCardRequest proto.InternalMessageInfo

func (m *AddCardRequest) GetPaymentMethod() string {
	if m != nil {
		return m.PaymentMethod
	}
	return ""
}

func (m *AddCardRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type AddCardResponse struct {
	AllCards             []*PaymentMethod `protobuf:"bytes,1,rep,name=all_cards,json=allCards,proto3" json:"all_cards,omitempty"`
	InvoiceSettings      *InvoiceSettings `protobuf:"bytes,2,opt,name=invoice_settings,json=invoiceSettings,proto3" json:"invoice_settings,omitempty"`
	Success              bool             `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AddCardResponse) Reset()         { *m = AddCardResponse{} }
func (m *AddCardResponse) String() string { return proto.CompactTextString(m) }
func (*AddCardResponse) ProtoMessage()    {}
func (*AddCardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a39aceed8019db, []int{7}
}

func (m *AddCardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCardResponse.Unmarshal(m, b)
}
func (m *AddCardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCardResponse.Marshal(b, m, deterministic)
}
func (m *AddCardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCardResponse.Merge(m, src)
}
func (m *AddCardResponse) XXX_Size() int {
	return xxx_messageInfo_AddCardResponse.Size(m)
}
func (m *AddCardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddCardResponse proto.InternalMessageInfo

func (m *AddCardResponse) GetAllCards() []*PaymentMethod {
	if m != nil {
		return m.AllCards
	}
	return nil
}

func (m *AddCardResponse) GetInvoiceSettings() *InvoiceSettings {
	if m != nil {
		return m.InvoiceSettings
	}
	return nil
}

func (m *AddCardResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type OnStripeChargeRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Items                *Items   `protobuf:"bytes,3,opt,name=items,proto3" json:"items,omitempty"`
	Currency             string   `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Subtotal             float64  `protobuf:"fixed64,5,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	Total                float64  `protobuf:"fixed64,6,opt,name=total,proto3" json:"total,omitempty"`
	OffSession           bool     `protobuf:"varint,7,opt,name=off_session,json=offSession,proto3" json:"off_session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnStripeChargeRequest) Reset()         { *m = OnStripeChargeRequest{} }
func (m *OnStripeChargeRequest) String() string { return proto.CompactTextString(m) }
func (*OnStripeChargeRequest) ProtoMessage()    {}
func (*OnStripeChargeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a39aceed8019db, []int{8}
}

func (m *OnStripeChargeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnStripeChargeRequest.Unmarshal(m, b)
}
func (m *OnStripeChargeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnStripeChargeRequest.Marshal(b, m, deterministic)
}
func (m *OnStripeChargeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnStripeChargeRequest.Merge(m, src)
}
func (m *OnStripeChargeRequest) XXX_Size() int {
	return xxx_messageInfo_OnStripeChargeRequest.Size(m)
}
func (m *OnStripeChargeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OnStripeChargeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OnStripeChargeRequest proto.InternalMessageInfo

func (m *OnStripeChargeRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *OnStripeChargeRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *OnStripeChargeRequest) GetItems() *Items {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *OnStripeChargeRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *OnStripeChargeRequest) GetSubtotal() float64 {
	if m != nil {
		return m.Subtotal
	}
	return 0
}

func (m *OnStripeChargeRequest) GetTotal() float64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *OnStripeChargeRequest) GetOffSession() bool {
	if m != nil {
		return m.OffSession
	}
	return false
}

type OnStripeChargeResponse struct {
	PaymentIntent        *PaymentIntent `protobuf:"bytes,1,opt,name=payment_intent,json=paymentIntent,proto3" json:"payment_intent,omitempty"`
	Success              bool           `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *OnStripeChargeResponse) Reset()         { *m = OnStripeChargeResponse{} }
func (m *OnStripeChargeResponse) String() string { return proto.CompactTextString(m) }
func (*OnStripeChargeResponse) ProtoMessage()    {}
func (*OnStripeChargeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a39aceed8019db, []int{9}
}

func (m *OnStripeChargeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnStripeChargeResponse.Unmarshal(m, b)
}
func (m *OnStripeChargeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnStripeChargeResponse.Marshal(b, m, deterministic)
}
func (m *OnStripeChargeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnStripeChargeResponse.Merge(m, src)
}
func (m *OnStripeChargeResponse) XXX_Size() int {
	return xxx_messageInfo_OnStripeChargeResponse.Size(m)
}
func (m *OnStripeChargeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OnStripeChargeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OnStripeChargeResponse proto.InternalMessageInfo

func (m *OnStripeChargeResponse) GetPaymentIntent() *PaymentIntent {
	if m != nil {
		return m.PaymentIntent
	}
	return nil
}

func (m *OnStripeChargeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SetupIntentRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	OnSession            bool     `protobuf:"varint,2,opt,name=on_session,json=onSession,proto3" json:"on_session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetupIntentRequest) Reset()         { *m = SetupIntentRequest{} }
func (m *SetupIntentRequest) String() string { return proto.CompactTextString(m) }
func (*SetupIntentRequest) ProtoMessage()    {}
func (*SetupIntentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a39aceed8019db, []int{10}
}

func (m *SetupIntentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetupIntentRequest.Unmarshal(m, b)
}
func (m *SetupIntentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetupIntentRequest.Marshal(b, m, deterministic)
}
func (m *SetupIntentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetupIntentRequest.Merge(m, src)
}
func (m *SetupIntentRequest) XXX_Size() int {
	return xxx_messageInfo_SetupIntentRequest.Size(m)
}
func (m *SetupIntentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetupIntentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetupIntentRequest proto.InternalMessageInfo

func (m *SetupIntentRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *SetupIntentRequest) GetOnSession() bool {
	if m != nil {
		return m.OnSession
	}
	return false
}

type SetupIntentResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ClientSecret         string   `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetupIntentResponse) Reset()         { *m = SetupIntentResponse{} }
func (m *SetupIntentResponse) String() string { return proto.CompactTextString(m) }
func (*SetupIntentResponse) ProtoMessage()    {}
func (*SetupIntentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a39aceed8019db, []int{11}
}

func (m *SetupIntentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetupIntentResponse.Unmarshal(m, b)
}
func (m *SetupIntentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetupIntentResponse.Marshal(b, m, deterministic)
}
func (m *SetupIntentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetupIntentResponse.Merge(m, src)
}
func (m *SetupIntentResponse) XXX_Size() int {
	return xxx_messageInfo_SetupIntentResponse.Size(m)
}
func (m *SetupIntentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetupIntentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetupIntentResponse proto.InternalMessageInfo

func (m *SetupIntentResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SetupIntentResponse) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

type StripeWebhook struct {
	Body                 []byte   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StripeWebhook) Reset()         { *m = StripeWebhook{} }
func (m *StripeWebhook) String() string { return proto.CompactTextString(m) }
func (*StripeWebhook) ProtoMessage()    {}
func (*StripeWebhook) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a39aceed8019db, []int{12}
}

func (m *StripeWebhook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StripeWebhook.Unmarshal(m, b)
}
func (m *StripeWebhook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StripeWebhook.Marshal(b, m, deterministic)
}
func (m *StripeWebhook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StripeWebhook.Merge(m, src)
}
func (m *StripeWebhook) XXX_Size() int {
	return xxx_messageInfo_StripeWebhook.Size(m)
}
func (m *StripeWebhook) XXX_DiscardUnknown() {
	xxx_messageInfo_StripeWebhook.DiscardUnknown(m)
}

var xxx_messageInfo_StripeWebhook proto.InternalMessageInfo

func (m *StripeWebhook) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type PaypalCreateOrderRequest struct {
	User                 string              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Items                *Items              `protobuf:"bytes,2,opt,name=items,proto3" json:"items,omitempty"`
	Currency             string              `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Total                float64             `protobuf:"fixed64,4,opt,name=total,proto3" json:"total,omitempty"`
	Intent               string              `protobuf:"bytes,5,opt,name=intent,proto3" json:"intent,omitempty"`
	ApplicationContext   *ApplicationContext `protobuf:"bytes,6,opt,name=application_context,json=applicationContext,proto3" json:"application_context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PaypalCreateOrderRequest) Reset()         { *m = PaypalCreateOrderRequest{} }
func (m *PaypalCreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*PaypalCreateOrderRequest) ProtoMessage()    {}
func (*PaypalCreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a39aceed8019db, []int{13}
}

func (m *PaypalCreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaypalCreateOrderRequest.Unmarshal(m, b)
}
func (m *PaypalCreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaypalCreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *PaypalCreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaypalCreateOrderRequest.Merge(m, src)
}
func (m *PaypalCreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_PaypalCreateOrderRequest.Size(m)
}
func (m *PaypalCreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaypalCreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaypalCreateOrderRequest proto.InternalMessageInfo

func (m *PaypalCreateOrderRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *PaypalCreateOrderRequest) GetItems() *Items {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *PaypalCreateOrderRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *PaypalCreateOrderRequest) GetTotal() float64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PaypalCreateOrderRequest) GetIntent() string {
	if m != nil {
		return m.Intent
	}
	return ""
}

func (m *PaypalCreateOrderRequest) GetApplicationContext() *ApplicationContext {
	if m != nil {
		return m.ApplicationContext
	}
	return nil
}

type PaypalProcessOrderRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	OrderId              string   `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaypalProcessOrderRequest) Reset()         { *m = PaypalProcessOrderRequest{} }
func (m *PaypalProcessOrderRequest) String() string { return proto.CompactTextString(m) }
func (*PaypalProcessOrderRequest) ProtoMessage()    {}
func (*PaypalProcessOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a39aceed8019db, []int{14}
}

func (m *PaypalProcessOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaypalProcessOrderRequest.Unmarshal(m, b)
}
func (m *PaypalProcessOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaypalProcessOrderRequest.Marshal(b, m, deterministic)
}
func (m *PaypalProcessOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaypalProcessOrderRequest.Merge(m, src)
}
func (m *PaypalProcessOrderRequest) XXX_Size() int {
	return xxx_messageInfo_PaypalProcessOrderRequest.Size(m)
}
func (m *PaypalProcessOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaypalProcessOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaypalProcessOrderRequest proto.InternalMessageInfo

func (m *PaypalProcessOrderRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *PaypalProcessOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type PaypalCreateOrderResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	OrderId              string   `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Href                 string   `protobuf:"bytes,3,opt,name=href,proto3" json:"href,omitempty"`
	Rel                  string   `protobuf:"bytes,4,opt,name=rel,proto3" json:"rel,omitempty"`
	Method               string   `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaypalCreateOrderResponse) Reset()         { *m = PaypalCreateOrderResponse{} }
func (m *PaypalCreateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*PaypalCreateOrderResponse) ProtoMessage()    {}
func (*PaypalCreateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a39aceed8019db, []int{15}
}

func (m *PaypalCreateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaypalCreateOrderResponse.Unmarshal(m, b)
}
func (m *PaypalCreateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaypalCreateOrderResponse.Marshal(b, m, deterministic)
}
func (m *PaypalCreateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaypalCreateOrderResponse.Merge(m, src)
}
func (m *PaypalCreateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_PaypalCreateOrderResponse.Size(m)
}
func (m *PaypalCreateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaypalCreateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaypalCreateOrderResponse proto.InternalMessageInfo

func (m *PaypalCreateOrderResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PaypalCreateOrderResponse) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *PaypalCreateOrderResponse) GetHref() string {
	if m != nil {
		return m.Href
	}
	return ""
}

func (m *PaypalCreateOrderResponse) GetRel() string {
	if m != nil {
		return m.Rel
	}
	return ""
}

func (m *PaypalCreateOrderResponse) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type PaypalWebhook struct {
	Body                 []byte   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaypalWebhook) Reset()         { *m = PaypalWebhook{} }
func (m *PaypalWebhook) String() string { return proto.CompactTextString(m) }
func (*PaypalWebhook) ProtoMessage()    {}
func (*PaypalWebhook) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a39aceed8019db, []int{16}
}

func (m *PaypalWebhook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaypalWebhook.Unmarshal(m, b)
}
func (m *PaypalWebhook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaypalWebhook.Marshal(b, m, deterministic)
}
func (m *PaypalWebhook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaypalWebhook.Merge(m, src)
}
func (m *PaypalWebhook) XXX_Size() int {
	return xxx_messageInfo_PaypalWebhook.Size(m)
}
func (m *PaypalWebhook) XXX_DiscardUnknown() {
	xxx_messageInfo_PaypalWebhook.DiscardUnknown(m)
}

var xxx_messageInfo_PaypalWebhook proto.InternalMessageInfo

func (m *PaypalWebhook) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a39aceed8019db, []int{17}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a39aceed8019db, []int{18}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreatePaymentRequest)(nil), "payment.CreatePaymentRequest")
	proto.RegisterType((*CreatePaymentResponse)(nil), "payment.CreatePaymentResponse")
	proto.RegisterType((*RetrievePaymentRequest)(nil), "payment.RetrievePaymentRequest")
	proto.RegisterType((*RetrievePaymentResponse)(nil), "payment.RetrievePaymentResponse")
	proto.RegisterType((*RefundRequest)(nil), "payment.RefundRequest")
	proto.RegisterType((*RefundResponse)(nil), "payment.RefundResponse")
	proto.RegisterType((*AddCardRequest)(nil), "payment.AddCardRequest")
	proto.RegisterType((*AddCardResponse)(nil), "payment.AddCardResponse")
	proto.RegisterType((*OnStripeChargeRequest)(nil), "payment.OnStripeChargeRequest")
	proto.RegisterType((*OnStripeChargeResponse)(nil), "payment.OnStripeChargeResponse")
	proto.RegisterType((*SetupIntentRequest)(nil), "payment.SetupIntentRequest")
	proto.RegisterType((*SetupIntentResponse)(nil), "payment.SetupIntentResponse")
	proto.RegisterType((*StripeWebhook)(nil), "payment.StripeWebhook")
	proto.RegisterType((*PaypalCreateOrderRequest)(nil), "payment.PaypalCreateOrderRequest")
	proto.RegisterType((*PaypalProcessOrderRequest)(nil), "payment.PaypalProcessOrderRequest")
	proto.RegisterType((*PaypalCreateOrderResponse)(nil), "payment.PaypalCreateOrderResponse")
	proto.RegisterType((*PaypalWebhook)(nil), "payment.PaypalWebhook")
	proto.RegisterType((*Response)(nil), "payment.Response")
	proto.RegisterType((*Empty)(nil), "payment.Empty")
}

func init() { proto.RegisterFile("payment/payment.proto", fileDescriptor_66a39aceed8019db) }

var fileDescriptor_66a39aceed8019db = []byte{
	// 1085 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x5b, 0x6b, 0xdc, 0xc6,
	0x17, 0x47, 0xbe, 0xfb, 0xf8, 0x3e, 0xb1, 0x37, 0x8a, 0xfe, 0x8e, 0xbd, 0x19, 0xfb, 0xdf, 0xb8,
	0x21, 0x58, 0xc4, 0x81, 0x16, 0x0a, 0x85, 0x06, 0x13, 0x8a, 0x7b, 0x8b, 0xd1, 0x1a, 0x4a, 0x1f,
	0xca, 0x32, 0x96, 0x66, 0x6d, 0x51, 0xad, 0x46, 0x9e, 0x99, 0xdd, 0xd6, 0x6f, 0x25, 0xaf, 0x85,
	0xbe, 0xf4, 0x33, 0xf4, 0x13, 0x15, 0xf2, 0x09, 0xfa, 0xd8, 0x0f, 0x51, 0xe6, 0x22, 0xad, 0x2e,
	0x7b, 0x49, 0x4b, 0x9f, 0xac, 0x39, 0xb7, 0xdf, 0x39, 0xbf, 0x33, 0x73, 0xce, 0x1a, 0xf6, 0x32,
	0x72, 0xdf, 0xa7, 0xa9, 0xf4, 0xed, 0xdf, 0xd3, 0x8c, 0x33, 0xc9, 0xd0, 0xb2, 0x3d, 0x7a, 0xbb,
	0xb9, 0x5e, 0x84, 0xb7, 0xb4, 0x4f, 0x8c, 0x7a, 0x24, 0xcd, 0xc8, 0x7d, 0x46, 0x92, 0xba, 0x54,
	0x48, 0x1e, 0x67, 0xd4, 0x4a, 0xf7, 0x6f, 0x18, 0xbb, 0x49, 0xa8, 0x4f, 0xb2, 0xd8, 0x27, 0x69,
	0xca, 0x24, 0x91, 0x31, 0x4b, 0x85, 0xd1, 0xe2, 0xcf, 0x60, 0xf7, 0x9c, 0x53, 0x22, 0xe9, 0xa5,
	0xf1, 0x0d, 0xe8, 0xdd, 0x80, 0x0a, 0x89, 0x10, 0x2c, 0x0c, 0x04, 0xe5, 0xae, 0xd3, 0x76, 0x4e,
	0x56, 0x03, 0xfd, 0x8d, 0x76, 0x61, 0x91, 0xf6, 0x49, 0x9c, 0xb8, 0x73, 0x5a, 0x68, 0x0e, 0xf8,
	0x7b, 0xd8, 0xab, 0x45, 0x10, 0x19, 0x4b, 0x05, 0x45, 0x2e, 0x2c, 0x8b, 0x41, 0x18, 0x52, 0x21,
	0x74, 0x94, 0x95, 0x20, 0x3f, 0xa2, 0x67, 0x90, 0xd7, 0xa7, 0x43, 0xad, 0x9d, 0x6d, 0x9f, 0xe6,
	0xe5, 0xe7, 0x41, 0x72, 0x03, 0xfc, 0x1c, 0x5a, 0x01, 0x95, 0x3c, 0xa6, 0xc3, 0xf7, 0x48, 0x11,
	0x77, 0xe1, 0x61, 0xc3, 0xfa, 0x3f, 0x4d, 0xe7, 0x35, 0x6c, 0x04, 0xb4, 0x37, 0x48, 0xa3, 0x69,
	0x44, 0xb5, 0x61, 0x4d, 0x72, 0x92, 0x0a, 0x12, 0x2a, 0xaa, 0x2d, 0x5d, 0x65, 0x11, 0xfe, 0xc5,
	0x81, 0xcd, 0x3c, 0xce, 0xcc, 0xfc, 0x9e, 0xc2, 0x12, 0xd7, 0xb6, 0x36, 0xbd, 0xad, 0x22, 0x3d,
	0x1b, 0xc2, 0xaa, 0xd1, 0x47, 0x55, 0xdc, 0x79, 0x6d, 0xbd, 0x5b, 0x58, 0x5f, 0x8d, 0x74, 0xd5,
	0x6c, 0xbe, 0x84, 0xcd, 0x57, 0x51, 0x74, 0x4e, 0x78, 0x51, 0xd5, 0xff, 0x61, 0xd3, 0x7a, 0x75,
	0xfb, 0x54, 0xde, 0xb2, 0xc8, 0xd6, 0xb7, 0x61, 0xa5, 0x5f, 0x6b, 0x61, 0x51, 0xfc, 0x5c, 0xa9,
	0x05, 0xbf, 0x3b, 0xb0, 0x55, 0x44, 0xb3, 0xb5, 0xbd, 0x84, 0x55, 0x92, 0x24, 0xdd, 0x90, 0xf0,
	0x48, 0x55, 0x37, 0x7f, 0xb2, 0x76, 0xd6, 0xaa, 0x73, 0x6c, 0x42, 0x06, 0x2b, 0x24, 0x49, 0x94,
	0xaf, 0x40, 0xe7, 0xb0, 0x1d, 0xa7, 0x43, 0x16, 0x87, 0xb4, 0x2b, 0xa8, 0x94, 0x71, 0x7a, 0x23,
	0x2c, 0x01, 0x6e, 0xe1, 0x7b, 0x61, 0x0c, 0x3a, 0x56, 0x1f, 0x6c, 0xc5, 0x55, 0x41, 0x99, 0xd5,
	0xf9, 0x0a, 0xab, 0xf8, 0x9d, 0x03, 0x7b, 0x6f, 0xd2, 0x8e, 0x7e, 0x2a, 0xe7, 0xb7, 0x84, 0xdf,
	0xd0, 0x7f, 0x7c, 0xf7, 0xd1, 0x31, 0x2c, 0xc6, 0x92, 0xf6, 0x85, 0xa5, 0x7a, 0x73, 0x94, 0x97,
	0x92, 0x06, 0x46, 0x89, 0x3c, 0x58, 0x09, 0x07, 0x9c, 0xd3, 0x34, 0xbc, 0x77, 0x17, 0xb4, 0x7b,
	0x71, 0x56, 0x3a, 0x31, 0xb8, 0x96, 0x4c, 0x92, 0xc4, 0x5d, 0x6c, 0x3b, 0x27, 0x4e, 0x50, 0x9c,
	0x15, 0xa6, 0x51, 0x2c, 0x69, 0x85, 0x39, 0xa0, 0x43, 0x58, 0x63, 0xbd, 0x5e, 0x57, 0x50, 0x21,
	0x54, 0x93, 0x97, 0x75, 0x55, 0xc0, 0x7a, 0xbd, 0x8e, 0x91, 0xe0, 0x3b, 0x68, 0xd5, 0xeb, 0xb2,
	0x6d, 0xf8, 0x74, 0xd4, 0xd5, 0x38, 0x95, 0xea, 0xbe, 0x3b, 0x3a, 0xef, 0x46, 0x2f, 0x2e, 0xb4,
	0xb6, 0xe8, 0xb6, 0x39, 0x96, 0xb9, 0x9c, 0xab, 0x72, 0xf9, 0x39, 0xa0, 0x0e, 0x95, 0x83, 0xcc,
	0xfa, 0x4d, 0xe1, 0xf1, 0x31, 0x00, 0x4b, 0x8b, 0xe4, 0x4d, 0x98, 0x55, 0x96, 0xe6, 0xb9, 0x5f,
	0xc1, 0x83, 0x4a, 0xa0, 0x99, 0x6f, 0xe3, 0x08, 0x36, 0xc2, 0x24, 0x56, 0x15, 0x09, 0x1a, 0x72,
	0x2a, 0x6d, 0x7f, 0xd6, 0x8d, 0xb0, 0xa3, 0x65, 0xf8, 0x08, 0x36, 0x0c, 0x1f, 0xdf, 0xd2, 0xeb,
	0x5b, 0xc6, 0x7e, 0x50, 0x99, 0x5d, 0xb3, 0xe8, 0x5e, 0x07, 0x5b, 0x0f, 0xf4, 0x37, 0xfe, 0xcb,
	0x01, 0xf7, 0x52, 0x8f, 0x53, 0x33, 0xce, 0xde, 0xf0, 0x88, 0xf2, 0x69, 0xa5, 0x14, 0xcd, 0x9f,
	0x7b, 0xdf, 0xe6, 0xcf, 0xd7, 0x9a, 0x5f, 0x34, 0x78, 0xa1, 0xdc, 0xe0, 0x16, 0x2c, 0xd9, 0xee,
	0x2c, 0x6a, 0x7b, 0x7b, 0x42, 0x5f, 0xc1, 0x03, 0x92, 0x65, 0x49, 0x1c, 0xea, 0x01, 0xde, 0x0d,
	0x59, 0x2a, 0xe9, 0x4f, 0x52, 0x5f, 0x8e, 0xb5, 0xb3, 0xff, 0x15, 0xe8, 0xaf, 0x46, 0x36, 0xe7,
	0xc6, 0x24, 0x40, 0xa4, 0x21, 0xc3, 0x5f, 0xc0, 0x23, 0x53, 0xed, 0x25, 0x67, 0x8a, 0xc9, 0x99,
	0xe5, 0x3e, 0x82, 0x15, 0xa6, 0x6c, 0xba, 0x71, 0x64, 0x49, 0x5e, 0xd6, 0xe7, 0x8b, 0x08, 0xff,
	0xea, 0xe4, 0xc1, 0x2a, 0xd4, 0xcd, 0x6c, 0xde, 0xe4, 0x90, 0x2a, 0x83, 0x5b, 0x4e, 0x7b, 0x96,
	0x32, 0xfd, 0x8d, 0xb6, 0x61, 0x9e, 0xd3, 0xc4, 0x3e, 0x21, 0xf5, 0xa9, 0xa8, 0xb2, 0xe3, 0xc9,
	0x52, 0x65, 0x4e, 0xaa, 0xe1, 0x26, 0x9f, 0x69, 0x0d, 0x3f, 0x86, 0x95, 0xd9, 0x39, 0xe2, 0x65,
	0x58, 0x7c, 0xdd, 0xcf, 0xe4, 0xfd, 0xd9, 0x3b, 0x80, 0x4d, 0xfb, 0x3c, 0x3a, 0x94, 0x0f, 0xe3,
	0x90, 0xa2, 0x6f, 0x60, 0xa3, 0xb2, 0xfa, 0xd0, 0xe3, 0xa2, 0x0b, 0xe3, 0x96, 0xaa, 0x77, 0x30,
	0x49, 0x6d, 0xb3, 0x18, 0xc2, 0x56, 0x6d, 0x7b, 0xa1, 0xc3, 0xd2, 0xac, 0x1f, 0xb7, 0x05, 0xbd,
	0xf6, 0x64, 0x03, 0x13, 0x15, 0xb7, 0xdf, 0xfe, 0xf1, 0xe7, 0x6f, 0x73, 0x1e, 0x76, 0xf5, 0x4f,
	0x80, 0xe1, 0x8b, 0xfc, 0xa7, 0x86, 0xcf, 0xad, 0x03, 0xfa, 0x0e, 0x96, 0xcc, 0x26, 0x41, 0xad,
	0xfa, 0x6a, 0xb1, 0x28, 0x0f, 0x1b, 0x72, 0x1b, 0xfc, 0x40, 0x07, 0x77, 0x71, 0xab, 0x19, 0x5c,
	0x07, 0x1c, 0xc2, 0x8e, 0x79, 0x7a, 0xa5, 0x67, 0x8d, 0x46, 0x97, 0xb5, 0x39, 0x35, 0xbc, 0xfd,
	0xf1, 0x4a, 0x8b, 0xf7, 0x81, 0xc6, 0x6b, 0xe3, 0x83, 0x3a, 0x9e, 0xf0, 0xcd, 0x33, 0xf1, 0x85,
	0xf2, 0x42, 0xbd, 0xfc, 0xc9, 0xdb, 0x55, 0x84, 0x46, 0x15, 0x54, 0x57, 0x9d, 0xe7, 0x36, 0x15,
	0x16, 0x0b, 0x6b, 0xac, 0x7d, 0xec, 0x35, 0xb1, 0xd4, 0x26, 0xf3, 0x49, 0x14, 0xa1, 0x3b, 0x58,
	0x2f, 0x8f, 0x5a, 0x34, 0x6a, 0xf1, 0xd8, 0xdd, 0xe2, 0x1d, 0x4e, 0xd4, 0xcf, 0xea, 0x96, 0xf0,
	0x43, 0x03, 0x91, 0xe6, 0x94, 0x5e, 0x51, 0x21, 0xf3, 0x0b, 0x3e, 0x6a, 0x5c, 0x65, 0xd2, 0x79,
	0x3b, 0xa5, 0xc6, 0x59, 0x84, 0x53, 0x8d, 0x70, 0x82, 0x8f, 0x1a, 0x08, 0xda, 0xd3, 0xff, 0xd1,
	0xb8, 0xfa, 0x92, 0x0a, 0xf9, 0x89, 0xf3, 0x0c, 0xfd, 0xec, 0x80, 0x67, 0x82, 0x56, 0xb6, 0xc3,
	0xbf, 0x40, 0xfe, 0x58, 0x23, 0xbf, 0xc0, 0xcf, 0x67, 0x20, 0x5b, 0xb1, 0x69, 0xa8, 0x4a, 0xe1,
	0xad, 0x03, 0x3b, 0x8d, 0x01, 0x83, 0x9e, 0x94, 0xd7, 0xd6, 0xd8, 0xb9, 0xed, 0xe1, 0x69, 0x26,
	0xb3, 0xae, 0x54, 0xe6, 0xeb, 0x69, 0xe4, 0x87, 0xda, 0x09, 0x49, 0x40, 0xcd, 0x89, 0x89, 0xea,
	0x08, 0x63, 0xc6, 0xe9, 0x38, 0x2a, 0x9e, 0x6a, 0xd0, 0x27, 0xf8, 0x70, 0x12, 0x68, 0x66, 0xe2,
	0xa0, 0x2c, 0x47, 0xd5, 0x11, 0x9b, 0xa4, 0x57, 0xe6, 0xdc, 0x38, 0x24, 0x5f, 0x23, 0x7d, 0x88,
	0x8f, 0x1b, 0x48, 0xda, 0xb3, 0x20, 0x5d, 0xc3, 0x2a, 0xb2, 0xd3, 0x9c, 0xeb, 0xf1, 0xf7, 0x6b,
	0x26, 0xe0, 0xc4, 0xfb, 0x55, 0x03, 0xb4, 0xf7, 0xeb, 0x7a, 0x49, 0xff, 0x27, 0xf2, 0xf2, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xfc, 0x14, 0x40, 0x37, 0x0b, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PaymentServiceClient interface {
	//
	// Payment
	CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error)
	RetrievePayment(ctx context.Context, in *RetrievePaymentRequest, opts ...grpc.CallOption) (*RetrievePaymentResponse, error)
	Refund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*RefundResponse, error)
	//
	// Stripe
	StripeSetupIntent(ctx context.Context, in *SetupIntentRequest, opts ...grpc.CallOption) (*SetupIntentResponse, error)
	StripeAddCard(ctx context.Context, in *AddCardRequest, opts ...grpc.CallOption) (*AddCardResponse, error)
	StripeCharge(ctx context.Context, in *OnStripeChargeRequest, opts ...grpc.CallOption) (*OnStripeChargeResponse, error)
	StripeTestWebhook(ctx context.Context, in *StripeWebhook, opts ...grpc.CallOption) (*Response, error)
	StripePaymentIntentWebhook(ctx context.Context, in *StripeWebhook, opts ...grpc.CallOption) (*Response, error)
	//
	// Paypal
	PaypalCreateOrder(ctx context.Context, in *PaypalCreateOrderRequest, opts ...grpc.CallOption) (*PaypalCreateOrderResponse, error)
	PaypalProcessOrder(ctx context.Context, in *PaypalProcessOrderRequest, opts ...grpc.CallOption) (*Response, error)
	PaypalOrderWebhook(ctx context.Context, in *PaypalWebhook, opts ...grpc.CallOption) (*Response, error)
	PaypalTestWebhook(ctx context.Context, in *PaypalWebhook, opts ...grpc.CallOption) (*Response, error)
}

type paymentServiceClient struct {
	cc *grpc.ClientConn
}

func NewPaymentServiceClient(cc *grpc.ClientConn) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error) {
	out := new(CreatePaymentResponse)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/CreatePayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) RetrievePayment(ctx context.Context, in *RetrievePaymentRequest, opts ...grpc.CallOption) (*RetrievePaymentResponse, error) {
	out := new(RetrievePaymentResponse)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/RetrievePayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) Refund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*RefundResponse, error) {
	out := new(RefundResponse)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/Refund", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) StripeSetupIntent(ctx context.Context, in *SetupIntentRequest, opts ...grpc.CallOption) (*SetupIntentResponse, error) {
	out := new(SetupIntentResponse)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/StripeSetupIntent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) StripeAddCard(ctx context.Context, in *AddCardRequest, opts ...grpc.CallOption) (*AddCardResponse, error) {
	out := new(AddCardResponse)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/StripeAddCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) StripeCharge(ctx context.Context, in *OnStripeChargeRequest, opts ...grpc.CallOption) (*OnStripeChargeResponse, error) {
	out := new(OnStripeChargeResponse)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/StripeCharge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) StripeTestWebhook(ctx context.Context, in *StripeWebhook, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/StripeTestWebhook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) StripePaymentIntentWebhook(ctx context.Context, in *StripeWebhook, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/StripePaymentIntentWebhook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) PaypalCreateOrder(ctx context.Context, in *PaypalCreateOrderRequest, opts ...grpc.CallOption) (*PaypalCreateOrderResponse, error) {
	out := new(PaypalCreateOrderResponse)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/PaypalCreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) PaypalProcessOrder(ctx context.Context, in *PaypalProcessOrderRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/PaypalProcessOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) PaypalOrderWebhook(ctx context.Context, in *PaypalWebhook, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/PaypalOrderWebhook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) PaypalTestWebhook(ctx context.Context, in *PaypalWebhook, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/PaypalTestWebhook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
type PaymentServiceServer interface {
	//
	// Payment
	CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error)
	RetrievePayment(context.Context, *RetrievePaymentRequest) (*RetrievePaymentResponse, error)
	Refund(context.Context, *RefundRequest) (*RefundResponse, error)
	//
	// Stripe
	StripeSetupIntent(context.Context, *SetupIntentRequest) (*SetupIntentResponse, error)
	StripeAddCard(context.Context, *AddCardRequest) (*AddCardResponse, error)
	StripeCharge(context.Context, *OnStripeChargeRequest) (*OnStripeChargeResponse, error)
	StripeTestWebhook(context.Context, *StripeWebhook) (*Response, error)
	StripePaymentIntentWebhook(context.Context, *StripeWebhook) (*Response, error)
	//
	// Paypal
	PaypalCreateOrder(context.Context, *PaypalCreateOrderRequest) (*PaypalCreateOrderResponse, error)
	PaypalProcessOrder(context.Context, *PaypalProcessOrderRequest) (*Response, error)
	PaypalOrderWebhook(context.Context, *PaypalWebhook) (*Response, error)
	PaypalTestWebhook(context.Context, *PaypalWebhook) (*Response, error)
}

// UnimplementedPaymentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPaymentServiceServer struct {
}

func (*UnimplementedPaymentServiceServer) CreatePayment(ctx context.Context, req *CreatePaymentRequest) (*CreatePaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePayment not implemented")
}
func (*UnimplementedPaymentServiceServer) RetrievePayment(ctx context.Context, req *RetrievePaymentRequest) (*RetrievePaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrievePayment not implemented")
}
func (*UnimplementedPaymentServiceServer) Refund(ctx context.Context, req *RefundRequest) (*RefundResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Refund not implemented")
}
func (*UnimplementedPaymentServiceServer) StripeSetupIntent(ctx context.Context, req *SetupIntentRequest) (*SetupIntentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StripeSetupIntent not implemented")
}
func (*UnimplementedPaymentServiceServer) StripeAddCard(ctx context.Context, req *AddCardRequest) (*AddCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StripeAddCard not implemented")
}
func (*UnimplementedPaymentServiceServer) StripeCharge(ctx context.Context, req *OnStripeChargeRequest) (*OnStripeChargeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StripeCharge not implemented")
}
func (*UnimplementedPaymentServiceServer) StripeTestWebhook(ctx context.Context, req *StripeWebhook) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StripeTestWebhook not implemented")
}
func (*UnimplementedPaymentServiceServer) StripePaymentIntentWebhook(ctx context.Context, req *StripeWebhook) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StripePaymentIntentWebhook not implemented")
}
func (*UnimplementedPaymentServiceServer) PaypalCreateOrder(ctx context.Context, req *PaypalCreateOrderRequest) (*PaypalCreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PaypalCreateOrder not implemented")
}
func (*UnimplementedPaymentServiceServer) PaypalProcessOrder(ctx context.Context, req *PaypalProcessOrderRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PaypalProcessOrder not implemented")
}
func (*UnimplementedPaymentServiceServer) PaypalOrderWebhook(ctx context.Context, req *PaypalWebhook) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PaypalOrderWebhook not implemented")
}
func (*UnimplementedPaymentServiceServer) PaypalTestWebhook(ctx context.Context, req *PaypalWebhook) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PaypalTestWebhook not implemented")
}

func RegisterPaymentServiceServer(s *grpc.Server, srv PaymentServiceServer) {
	s.RegisterService(&_PaymentService_serviceDesc, srv)
}

func _PaymentService_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/CreatePayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreatePayment(ctx, req.(*CreatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_RetrievePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrievePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).RetrievePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/RetrievePayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).RetrievePayment(ctx, req.(*RetrievePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_Refund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).Refund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/Refund",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).Refund(ctx, req.(*RefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_StripeSetupIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).StripeSetupIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/StripeSetupIntent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).StripeSetupIntent(ctx, req.(*SetupIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_StripeAddCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).StripeAddCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/StripeAddCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).StripeAddCard(ctx, req.(*AddCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_StripeCharge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnStripeChargeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).StripeCharge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/StripeCharge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).StripeCharge(ctx, req.(*OnStripeChargeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_StripeTestWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StripeWebhook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).StripeTestWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/StripeTestWebhook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).StripeTestWebhook(ctx, req.(*StripeWebhook))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_StripePaymentIntentWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StripeWebhook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).StripePaymentIntentWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/StripePaymentIntentWebhook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).StripePaymentIntentWebhook(ctx, req.(*StripeWebhook))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_PaypalCreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaypalCreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).PaypalCreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/PaypalCreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).PaypalCreateOrder(ctx, req.(*PaypalCreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_PaypalProcessOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaypalProcessOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).PaypalProcessOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/PaypalProcessOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).PaypalProcessOrder(ctx, req.(*PaypalProcessOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_PaypalOrderWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaypalWebhook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).PaypalOrderWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/PaypalOrderWebhook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).PaypalOrderWebhook(ctx, req.(*PaypalWebhook))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_PaypalTestWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaypalWebhook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).PaypalTestWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/PaypalTestWebhook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).PaypalTestWebhook(ctx, req.(*PaypalWebhook))
	}
	return interceptor(ctx, in, info, handler)
}

var _PaymentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "payment.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePayment",
			Handler:    _PaymentService_CreatePayment_Handler,
		},
		{
			MethodName: "RetrievePayment",
			Handler:    _PaymentService_RetrievePayment_Handler,
		},
		{
			MethodName: "Refund",
			Handler:    _PaymentService_Refund_Handler,
		},
		{
			MethodName: "StripeSetupIntent",
			Handler:    _PaymentService_StripeSetupIntent_Handler,
		},
		{
			MethodName: "StripeAddCard",
			Handler:    _PaymentService_StripeAddCard_Handler,
		},
		{
			MethodName: "StripeCharge",
			Handler:    _PaymentService_StripeCharge_Handler,
		},
		{
			MethodName: "StripeTestWebhook",
			Handler:    _PaymentService_StripeTestWebhook_Handler,
		},
		{
			MethodName: "StripePaymentIntentWebhook",
			Handler:    _PaymentService_StripePaymentIntentWebhook_Handler,
		},
		{
			MethodName: "PaypalCreateOrder",
			Handler:    _PaymentService_PaypalCreateOrder_Handler,
		},
		{
			MethodName: "PaypalProcessOrder",
			Handler:    _PaymentService_PaypalProcessOrder_Handler,
		},
		{
			MethodName: "PaypalOrderWebhook",
			Handler:    _PaymentService_PaypalOrderWebhook_Handler,
		},
		{
			MethodName: "PaypalTestWebhook",
			Handler:    _PaymentService_PaypalTestWebhook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment/payment.proto",
}
