// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment/paypal.proto

package payment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApplicationContext struct {
	LandingPage          string   `protobuf:"bytes,1,opt,name=landing_page,json=landingPage,proto3" json:"landing_page,omitempty"`
	ReturnUrl            string   `protobuf:"bytes,2,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	CancelUrl            string   `protobuf:"bytes,3,opt,name=cancel_url,json=cancelUrl,proto3" json:"cancel_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationContext) Reset()         { *m = ApplicationContext{} }
func (m *ApplicationContext) String() string { return proto.CompactTextString(m) }
func (*ApplicationContext) ProtoMessage()    {}
func (*ApplicationContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_4660c9391f8eb4a5, []int{0}
}

func (m *ApplicationContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationContext.Unmarshal(m, b)
}
func (m *ApplicationContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationContext.Marshal(b, m, deterministic)
}
func (m *ApplicationContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationContext.Merge(m, src)
}
func (m *ApplicationContext) XXX_Size() int {
	return xxx_messageInfo_ApplicationContext.Size(m)
}
func (m *ApplicationContext) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationContext.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationContext proto.InternalMessageInfo

func (m *ApplicationContext) GetLandingPage() string {
	if m != nil {
		return m.LandingPage
	}
	return ""
}

func (m *ApplicationContext) GetReturnUrl() string {
	if m != nil {
		return m.ReturnUrl
	}
	return ""
}

func (m *ApplicationContext) GetCancelUrl() string {
	if m != nil {
		return m.CancelUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*ApplicationContext)(nil), "payment.ApplicationContext")
}

func init() { proto.RegisterFile("payment/paypal.proto", fileDescriptor_4660c9391f8eb4a5) }

var fileDescriptor_4660c9391f8eb4a5 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x48, 0xac, 0xcc,
	0x4d, 0xcd, 0x2b, 0xd1, 0x2f, 0x48, 0xac, 0x2c, 0x48, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x87, 0x8a, 0x2a, 0x95, 0x72, 0x09, 0x39, 0x16, 0x14, 0xe4, 0x64, 0x26, 0x27, 0x96,
	0x64, 0xe6, 0xe7, 0x39, 0xe7, 0xe7, 0x95, 0xa4, 0x56, 0x94, 0x08, 0x29, 0x72, 0xf1, 0xe4, 0x24,
	0xe6, 0xa5, 0x64, 0xe6, 0xa5, 0xc7, 0x17, 0x24, 0xa6, 0xa7, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0x71, 0x43, 0xc5, 0x02, 0x12, 0xd3, 0x53, 0x85, 0x64, 0xb9, 0xb8, 0x8a, 0x52, 0x4b, 0x4a,
	0x8b, 0xf2, 0xe2, 0x4b, 0x8b, 0x72, 0x24, 0x98, 0xc0, 0x0a, 0x38, 0x21, 0x22, 0xa1, 0x45, 0x39,
	0x20, 0xe9, 0xe4, 0xc4, 0xbc, 0xe4, 0xd4, 0x1c, 0xb0, 0x34, 0x33, 0x44, 0x1a, 0x22, 0x12, 0x5a,
	0x94, 0x93, 0xc4, 0x06, 0x76, 0x86, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x80, 0xea, 0x15,
	0x9e, 0x00, 0x00, 0x00,
}
